Release/hip 820. Added 3 methods
hgraph-io/hedera-walletconnect-utils pull request #62
Opened 2023-11-22 15:36 UTC by BeeJeeNinja

• signQueryAndSend - ready
• hedera_signMessage - ready
• hedera_getNodeAddresses - ready, but still with encoding issues (I guess we need to merge it as is)

2023-11-22 23:49 UTC, hgraphql requested changes
relatively minor changes requested for consistency

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +} from '../../../lib/index'
I don't think we need this change?

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +  const activeSession = signClient.session
was there trouble using the globally available session?
if not, let's use that
 https://github.com/hgraph-io/hedera-walletconnect-utils/blob/9fe6d5a85ef355c42ecc6e918d83ca8395eb3231/src/examples/typescript/dapp/main.ts#L29

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +  }
let's just add a required field in the html for both of these messages, then we can reduce the number of lines of code someone has to go through to see the steps

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +  const base64Query = Buffer.from(query.toBytes()).toString('base64');
great for this PR. we can move this to a helper in the lib just like we have for transaction

2023-11-22 23:49 UTC, hgraphql commented on src/lib/wallet/index.ts
> +    const network = chainId.split(':')[1];
added this ticket regarding prettier rules - https://github.com/orgs/hgraph-io/projects/4?pane=issue&itemId=44613969

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +    .find((session: { expiry: number }) => session.expiry > Date.now() / 1000)
same here, if we can use the activeSession as defined below, let's do that

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +    .find((session: { expiry: number }) => session.expiry > Date.now() / 1000)
activeSession as defined above

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/wallet/main.ts
> +import { Wallet, HederaChainId } from '../../../lib'
do we need to make this change?

2023-11-22 23:49 UTC, hgraphql commented on src/examples/typescript/wallet/main.ts
> +    const { chainId } = wallet.parseSessionRequest(event)
we need an end user to confirm whether or not they will accept the proposed transaction

2023-11-22 23:49 UTC, hgraphql commented on src/lib/wallet/index.ts
> +    const { id, topic, method, body } = this.parseSessionRequest(event);
no need to make this change

2023-11-23 14:33 UTC, BeeJeeNinja commented on src/examples/typescript/dapp/main.ts
> +} from '../../../lib/index'
no, we don't. I have removed it, but I still have build issues. I will try to deal with it myself

2023-11-23 14:56 UTC, BeeJeeNinja commented
pushed a new commit, please check

2023-11-23 15:24 UTC, hgraphql approved these changes, later dismissed
lgtm, left a few additional comments for further discussion

2023-11-23 15:24 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +  queryToBase64String,
nice!

2023-11-23 15:24 UTC, hgraphql commented on src/examples/typescript/dapp/main.ts
> +    .find((session: { expiry: number }) => session.expiry > Date.now() / 1000)
do we need to redefine this?

2023-11-23 15:24 UTC, hgraphql commented on src/lib/wallet/index.ts
> +    const methodsWithoutTransaction = [
should be named methodsWithTransaction

2023-11-23 15:24 UTC, hgraphql commented on src/lib/wallet/index.ts
> +    let query: Query<any> | undefined;
nice!  I noticed query required a type parameter as well...in contrast to `Transaction`

2023-11-23 15:24 UTC, hgraphql commented on src/lib/wallet/index.ts
> +    const body = transaction ?? query ?? requestParams;
I'm not sure if we want to conflate params with body here

2023-11-26 19:05 UTC, hgraphql approved these changes
adding functionality for 3 methods

2023-11-26 19:06 UTC, merged